// eslint-disable-next-line import/prefer-default-export
export const CITY_LIST = {
  a: [
    { name: '鞍山', py: 'anshan', code: '178' },
    { name: '安庆', py: 'anqing', code: '177' },
    { name: '安阳', py: 'anyang', code: '181' },
    { name: '安顺', py: 'anshun', code: '179' },
    { name: '安康', py: 'ankang', code: '171' },
    { name: '阿克苏', py: 'akesu', code: '173' },
    { name: '阿勒泰', py: 'aletai', code: '175' },
    { name: '阿拉尔', py: 'alaer', code: '20943' },
  ],
  b: [
    { name: '北京', py: 'beijing', code: '1' },
    { name: '保定', py: 'baoding', code: '185' },
    { name: '包头', py: 'baotou', code: '141' },
    { name: '本溪', py: 'benxi', code: '1155' },
    { name: '蚌埠', py: 'bengbu', code: '182' },
    { name: '北海', py: 'beihai', code: '189' },
    { name: '滨州', py: 'binzhou', code: '1820' },
    { name: '宝鸡', py: 'baoji', code: '112' },
    { name: '亳州', py: 'bozhou', code: '1078' },
    { name: '巴彦淖尔', py: 'bayannaoer', code: '3887' },
    { name: '白山', py: 'baishan', code: '3886' },
    { name: '白城', py: 'baicheng', code: '1116' },
    { name: '百色', py: 'baise', code: '1140' },
    { name: '巴中', py: 'bazhong', code: '3966' },
    { name: '毕节', py: 'bijie', code: '22031' },
    { name: '保山', py: 'baoshan', code: '197' },
    { name: '白银', py: 'baiyin', code: '1541' },
    { name: '巴音郭楞', py: 'bayinguoleng', code: '21130' },
    { name: '博尔塔拉', py: 'boertala', code: '21468' },
  ],
  c: [
    { name: '成都', py: 'chengdu', code: '28' },
    { name: '重庆', py: 'chongqing', code: '4' },
    { name: '长沙', py: 'changsha', code: '206' },
    { name: '长春', py: 'changchun', code: '158' },
    { name: '常州', py: 'changzhou', code: '213' },
    { name: '沧州', py: 'cangzhou', code: '216' },
    { name: '承德', py: 'chengde', code: '562' },
    { name: '常德', py: 'changde', code: '201' },
    { name: '郴州', py: 'chenzhou', code: '612' },
    { name: '长治', py: 'changzhi', code: '137' },
    { name: '滁州', py: 'chuzhou', code: '214' },
    { name: '池州', py: 'chizhou', code: '218' },
    { name: '赤峰', py: 'chifeng', code: '202' },
    { name: '潮州', py: 'chaozhou', code: '215' },
    { name: '崇左', py: 'chongzuo', code: '1896' },
    { name: '澄迈', py: 'chengmai', code: '20836' },
    { name: '楚雄', py: 'chuxiong', code: '21658' },
    { name: '昌都地区', py: 'changdudiqu' },
    { name: '昌吉', py: 'changji', code: '22032' },
  ],
  d: [
    { name: '大连', py: 'dalian', code: '6' },
    { name: '东莞', py: 'dongguan', code: '223' },
    { name: '大庆', py: 'daqing', code: '231' },
    { name: '东营', py: 'dongying', code: '236' },
    { name: '德州', py: 'dezhou', code: '1370' },
    { name: '大同', py: 'datong', code: '136' },
    { name: '大理', py: 'dali', code: '669326' },
    { name: '丹东', py: 'dandong', code: '221' },
    { name: '德阳', py: 'deyang', code: '237' },
    { name: '儋州', py: 'danzhou', code: '57' },
    { name: '东方', py: 'dongfang', code: '48' },
    { name: '定安', py: 'dingan', code: '50' },
    { name: '达州', py: 'dazhou', code: '1233' },
    { name: '德宏', py: 'dehong', code: '365' },
    { name: '迪庆', py: 'diqing', code: '93' },
    { name: '定西', py: 'dingxi', code: '1021' },
  ],
  e: [
    { name: '鄂尔多斯', py: 'eerduosi', code: '3976' },
    { name: '鄂州', py: 'ezhou', code: '992' },
    { name: '恩施', py: 'enshi', code: '245' },
  ],
  f: [
    { name: '福州', py: 'fuzhou', code: '258' },
    { name: '佛山', py: 'foshan', code: '251' },
    { name: '抚顺', py: 'fushun', code: '252' },
    { name: '阜新', py: 'fuxin', code: '254' },
    { name: '阜阳', py: 'fuyang', code: '257' },
    { name: '抚州', py: 'fuzhou', code: '3884' },
    { name: '防城港', py: 'fangchenggang', code: '1677' },
  ],
  g: [
    { name: '广州', py: 'guangzhou', code: '32' },
    { name: '贵阳', py: 'guiyang', code: '38' },
    { name: '桂林', py: 'guilin', code: '33' },
    { name: '贵港', py: 'guigang', code: '1518' },
    { name: '广元', py: 'guangyuan', code: '267' },
    { name: '广安', py: 'guangan', code: '1100' },
    { name: '甘孜', py: 'ganzi', code: '4124' },
    { name: '甘南', py: 'gannan', code: '7844' },
    { name: '固原', py: 'guyuan', code: '321' },
    { name: '果洛', py: 'guoluo', code: '21862' },
  ],
  h: [
    { name: '杭州', py: 'hangzhou', code: '17' },
    { name: '合肥', py: 'hefei', code: '278' },
    { name: '哈尔滨', py: 'haerbin', code: '5' },
    { name: '呼和浩特', py: 'huhehaote', code: '103' },
    { name: '邯郸', py: 'handan', code: '275' },
    { name: '葫芦岛', py: 'huludao', code: '1050' },
    { name: '衡水', py: 'hengshui', code: '290' },
    { name: '海口', py: 'haikou', code: '42' },
    { name: '湖州', py: 'huzhou', code: '86' },
    { name: '淮安', py: 'huaian', code: '577' },
    { name: '衡阳', py: 'hengyuang', code: '297' },
    { name: '汉中', py: 'hanzhong', code: '129' },
    { name: '菏泽', py: 'heze', code: '1074' },
    { name: '惠州', py: 'huizhou', code: '299' },
    { name: '黄山', py: 'huangshan', code: '23' },
    { name: '淮南', py: 'huainan', code: '287' },
    { name: '淮北', py: 'huaibei', code: '272' },
    { name: '呼伦贝尔', py: 'hulunbeier', code: '4255' },
    { name: '兴安盟', py: 'xinganmeng', code: '21021' },
    { name: '鹤岗', py: 'hegang', code: '1611' },
    { name: '黑河', py: 'heihe', code: '281' },
    { name: '黄石', py: 'huangshi', code: '292' },
    { name: '黄冈', py: 'huanggang', code: '3885' },
    { name: '怀化', py: 'huaihua', code: '282' },
    { name: '鹤壁', py: 'hebi', code: '951' },
    { name: '河源', py: 'heyuan', code: '693' },
    { name: '贺州', py: 'hezhou', code: '4146' },
    { name: '河池', py: 'hechi', code: '3969' },
  ],
  i: [{ name: '伊犁州', py: 'yilizhou' }],
  j: [
    { name: '济南', py: 'jinan', code: '144' },
    { name: '锦州', py: 'jinzhou', code: '327' },
    { name: '晋中', py: 'jinzhong', code: '1453' },
    { name: '吉林', py: 'jilin', code: '159' },
    { name: '济宁', py: 'jining', code: '318' },
    { name: '金华', py: 'jinhua', code: '308' },
    { name: '嘉兴', py: 'jiaxing', code: '571' },
    { name: '九江', py: 'jiujiang', code: '24' },
    { name: '荆州', py: 'jingzhou', code: '328' },
    { name: '景德镇', py: 'jingdezhen', code: '305' },
    { name: '江门', py: 'jiangmen', code: '316' },
    { name: '揭阳', py: 'jieyang', code: '956' },
    { name: '焦作', py: 'jiaozuo', code: '1093' },
    { name: '晋城', py: 'jincheng', code: '1092' },
    { name: '鸡西', py: 'jixi', code: '157' },
    { name: '佳木斯', py: 'jiamusi', code: '317' },
    { name: '吉安', py: 'jian', code: '933' },
    { name: '荆门', py: 'jingmen', code: '1121' },
    { name: '济源', py: 'jiyuan', code: '1454' },
    { name: '金昌', py: 'jinchang', code: '1158' },
    { name: '酒泉', py: 'jiuquan', code: '662' },
  ],
  k: [
    { name: '昆明', py: 'kunming', code: '34' },
    { name: '开封', py: 'kaifeng', code: '331' },
    { name: '克拉玛依', py: 'kelamayi', code: '166' },
  ],
  l: [
    { name: '洛阳', py: 'luoyang', code: '350' },
    { name: '兰州', py: 'lanzhou', code: '100' },
    { name: '廊坊', py: 'langfang', code: '340' },
    { name: '临沂', py: 'linyi', code: '569' },
    { name: '辽阳', py: 'liaoyang', code: '351' },
    { name: '连云港', py: 'lianyungang', code: '353' },
    { name: '泸州', py: 'luzhou', code: '355' },
    { name: '莱芜', py: 'laiwu', code: '1452' },
    { name: '聊城', py: 'liaocheng', code: '1071' },
    { name: '柳州', py: 'liuzhou', code: '354' },
    { name: '丽江', py: 'lijiang', code: '37' },
    { name: '丽水', py: 'lishui', code: '346' },
    { name: '拉萨', py: 'lasa', code: '41' },
    { name: '六安', py: 'liuan', code: '1705' },
    { name: '临汾', py: 'lifen', code: '139' },
    { name: '吕梁', py: 'lvliang', code: '7631' },
    { name: '辽源', py: 'liaoyuan', code: '352' },
    { name: '龙岩', py: 'longyan', code: '348' },
    { name: '娄底', py: 'loudi', code: '918' },
    { name: '漯河', py: 'luohe', code: '1088' },
    { name: '来宾', py: 'laibin', code: '1892' },
    { name: '临高', py: 'lingao', code: '20868' },
    { name: '乐山', py: 'leshan', code: '345' },
    { name: '六盘水', py: 'liupanshui', code: '605' },
    { name: '临沧', py: 'lincang', code: '1236' },
    { name: '陇南', py: 'longnan', code: '7707' },
  ],
  m: [
    { name: '绵阳', py: 'mianyang', code: '370' },
    { name: '马鞍山', py: 'maanshan', code: '1024' },
    { name: '牡丹江', py: 'mudanjiang', code: '150' },
    { name: '茂名', py: 'maoming', code: '1105' },
    { name: '梅州', py: 'meizhou', code: '3053' },
    { name: '眉山', py: 'meishan', code: '1148' },
  ],
  n: [
    { name: '南京', py: 'nanjing', code: '12' },
    { name: '宁波', py: 'ningbo', code: '375' },
    { name: '南宁', py: 'naning', code: '380' },
    { name: '南昌', py: 'nanchang', code: '376' },
    { name: '南充', py: 'nanchong', code: '377' },
    { name: '南通', py: 'nantong', code: '82' },
    { name: '南阳', py: 'nanyang', code: '385' },
    { name: '宁德', py: 'ningde', code: '378' },
    { name: '南平', py: 'nanping', code: '606' },
    { name: '内江', py: 'neijinag', code: '1597' },
  ],
  p: [
    { name: '平顶山', py: 'pingdingshan', code: '3222' },
    { name: '攀枝花', py: 'panzhihua', code: '1097' },
    { name: '莆田', py: 'putian', code: '667' },
    { name: '盘锦', py: 'panjin', code: '387' },
    { name: '濮阳', py: 'puyang', code: '1232' },
    { name: '萍乡', py: 'pingxiang', code: '1840' },
    { name: '普洱', py: 'puer', code: '3996' },
    { name: '平凉', py: 'pingliang', code: '388' },
  ],
  q: [
    { name: '青岛', py: 'qingdao', code: '7' },
    { name: '泉州', py: 'quanzhou', code: '406' },
    { name: '秦皇岛', py: 'qinhuangdao', code: '147' },
    { name: '齐齐哈尔', py: 'qiqihaer', code: '149' },
    { name: '曲靖', py: 'qujing', code: '985' },
    { name: '衢州', py: 'quzhou', code: '407' },
    { name: '清远', py: 'qingyuan', code: '1422' },
    { name: '七台河', py: 'qitaihe', code: '1599' },
    { name: '潜江', py: 'qianjiang', code: '4154' },
    { name: '钦州', py: 'qinzhou', code: '1899' },
    { name: '琼海', py: 'qionghai', code: '52' },
    { name: '庆阳', py: 'qingyang', code: '404' },
  ],
  r: [{ name: '日照', py: 'rizhao', code: '1106' }],
  s: [
    { name: '深圳', py: 'shenzhen', code: '30' },
    { name: '上海', py: 'shanghai', code: '2' },
    { name: '沈阳', py: 'shenyang', code: '451' },
    { name: '石家庄', py: 'shijiazhuang', code: '428' },
    { name: '苏州', py: 'suzhou', code: '14' },
    { name: '三亚', py: 'sanya', code: '43' },
    { name: '绍兴', py: 'shaoxing', code: '22' },
    { name: '绥化', py: 'suihua', code: '1128' },
    { name: '四平', py: 'siping', code: '440' },
    { name: '宿迁', py: 'suqian', code: '1472' },
    { name: '汕头', py: 'shantou', code: '447' },
    { name: '商丘', py: 'shangqiu', code: '441' },
    { name: '石河子', py: 'shihezi', code: '426' },
    { name: '宿州', py: 'suzhou', code: '521' },
    { name: '朔州', py: 'shuozhou', code: '1317' },
    { name: '松原', py: 'songyuan', code: '1303' },
    { name: '双鸭山', py: 'shuangyashan', code: '1617' },
    { name: '上饶', py: 'shangrao', code: '411' },
    { name: '三明', py: 'sanming', code: '437' },
    { name: '十堰', py: 'shiyan', code: '452' },
    { name: '随州', py: 'suizhou', code: '1117' },
    { name: '神农架林区', py: 'shennongjialinqu' },
    { name: '邵阳', py: 'shaoyang', code: '1111' },
    { name: '三门峡', py: 'sanmenxia', code: '436' },
    { name: '韶关', py: 'shaoguan', code: '422' },
    { name: '汕尾', py: 'shanwei', code: '1436' },
    { name: '遂宁', py: 'suining', code: '1371' },
    { name: '商洛', py: 'shangluo', code: '7551' },
    { name: '石嘴山', py: 'shizuishan', code: '4216' },
    { name: '三沙', py: 'sansha', code: '78689' },
  ],
  t: [
    { name: '天津', py: 'tianjin', code: '3' },
    { name: '太原', py: 'taiyuan', code: '105' },
    { name: '唐山', py: 'tangshan', code: '468' },
    { name: '铁岭', py: 'tieling', code: '1048' },
    { name: '台州', py: 'taizhou', code: '578' },
    { name: '泰州', py: 'taizhou', code: '579' },
    { name: '泰安', py: 'taian', code: '454' },
    { name: '天水', py: 'tianshui', code: '464' },
    { name: '铜陵', py: 'tongling', code: '459' },
    { name: '通辽', py: 'tongliao', code: '458' },
    { name: '通化', py: 'tonghua', code: '456' },
    { name: '天门', py: 'tianmen', code: '3920' },
    { name: '铜川', py: 'tongchuan', code: '118' },
  ],
  w: [
    { name: '武汉', py: 'wuhan', code: '477' },
    { name: '威海', py: 'weihai', code: '479' },
    { name: '无锡', py: 'wuxi', code: '13' },
    { name: '乌鲁木齐', py: 'wulumuqi', code: '39' },
    { name: '潍坊', py: 'weifang', code: '475' },
    { name: '温州', py: 'wenzhou', code: '491' },
    { name: '芜湖', py: 'wuhu', code: '478' },
    { name: '乌海', py: 'wuhai', code: '1133' },
    { name: '乌兰察布', py: 'wulanchabu', code: '7518' },
    { name: '梧州', py: 'wuzhou', code: '492' },
    { name: '五指山', py: 'wuzhishan', code: '46' },
    { name: '文昌', py: 'wenchang', code: '44' },
    { name: '万宁', py: 'wanning', code: '45' },
    { name: '文山州', py: 'wenshanzhou' },
    { name: '渭南', py: 'weinan', code: '1030' },
    { name: '武威', py: 'wuwei', code: '664' },
    { name: '吴忠', py: 'wuzhong', code: '7587' },
  ],
  x: [
    { name: '西安', py: 'xian', code: '10' },
    { name: '西宁', py: 'xining', code: '124' },
    { name: '厦门', py: 'xiamen', code: '25' },
    { name: '徐州', py: 'xuzhou', code: '512' },
    { name: '湘潭', py: 'xiangtan', code: '598' },
    { name: '邢台', py: 'xingtai', code: '947' },
    { name: '襄阳', py: 'xiangyang', code: '496' },
    { name: '新乡', py: 'xinxiang', code: '507' },
    { name: '许昌', py: 'xuchang', code: '1094' },
    { name: '咸阳', py: 'xianyang', code: '111' },
    { name: '新余', py: 'xinyu', code: '603' },
    { name: '宣城', py: 'xuancheng', code: '1006' },
    { name: '忻州', py: 'xinzhou', code: '513' },
    { name: '锡林郭勒盟', py: 'xilinguolemeng', code: '7576' },
    { name: '孝感', py: 'xiaogan', code: '1490' },
    { name: '咸宁', py: 'xianning', code: '937' },
    { name: '仙桃', py: 'xiantao', code: '1882' },
    { name: '湘西', py: 'xiangxi', code: '3910' },
    { name: '信阳', py: 'xinyang', code: '510' },
  ],
  y: [
    { name: '烟台', py: 'yantai', code: '533' },
    { name: '银川', py: 'yinchuan', code: '99' },
    { name: '宜昌', py: 'yichang', code: '515' },
    { name: '岳阳', py: 'yueyang', code: '539' },
    { name: '营口', py: 'yingkou', code: '1300' },
    { name: '扬州', py: 'yanghzou', code: '15' },
    { name: '盐城', py: 'yancheng', code: '1200' },
    { name: '运城', py: 'yuncheng', code: '140' },
    { name: '宜宾', py: 'yibin', code: '514' },
    { name: '阳泉', py: 'yangquan', code: '907' },
    { name: '延吉', py: 'yanji', code: '523' },
    { name: '玉林', py: 'yulin', code: '1113' },
    { name: '延安', py: 'yanan', code: '110' },
    { name: '榆林', py: 'yulin', code: '527' },
    { name: '伊春', py: 'yichun', code: '517' },
    { name: '鹰潭', py: 'yingtan', code: '534' },
    { name: '宜春', py: 'yichun', code: '518' },
    { name: '益阳', py: 'yiyang', code: '1125' },
    { name: '永州', py: 'yongzhou', code: '970' },
    { name: '阳江', py: 'yangjiang', code: '692' },
    { name: '云浮', py: 'yunfu', code: '3933' },
    { name: '雅安', py: 'yaan', code: '3277' },
    { name: '玉溪', py: 'yuxi', code: '186' },
  ],
  z: [
    { name: '郑州', py: 'zhengzhou', code: '559' },
    { name: '遵义', py: 'zunyi', code: '558' },
    { name: '株洲', py: 'zhuzhou', code: '601' },
    { name: '淄博', py: 'zibo', code: '542' },
    { name: '张家口', py: 'zhangjiakou', code: '550' },
    { name: '珠海', py: 'zhuhai', code: '31' },
    { name: '镇江', py: 'zhenjiang', code: '16' },
    { name: '周口', py: 'zhoukou', code: '3221' },
    { name: '中山', py: 'zhongshna', code: '553' },
    { name: '漳州', py: 'zhangzhou', code: '560' },
    { name: '舟山', py: 'zhoushan', code: '19' },
    { name: '湛江', py: 'zhanjiang', code: '547' },
    { name: '肇庆', py: 'zhaoqing', code: '552' },
    { name: '枣庄', py: 'zaozhuang', code: '614' },
    { name: '张家界', py: 'zhangjiajie', code: '27' },
    { name: '驻马店', py: 'zhumadian', code: '551' },
    { name: '自贡', py: 'zigong', code: '544' },
    { name: '资阳', py: 'ziyang', code: '1560' },
    { name: '昭通', py: 'zhaotong', code: '555' },
    { name: '张掖', py: 'zhangye', code: '663' },
    { name: '中卫', py: 'zhongwei', code: '556' },
  ],
};
